name: 'elm-review'
description: 'Use elm-review to check code quality'
author: 'Phill Sparks'
branding:
  icon: check-circle
  color: orange
inputs:
  name:
    description: 'This action creates its own entry in the checks, you can change the name with this input.'
    required: true
    default: 'elm-review'
  elm_review:
    description: 'Specify the path to elm-review.'
    required: true
    default: 'elm-review'
  elm_review_config:
    description: 'Use the review configuration in the specified directory instead of the one found in the current directory or one of its parents.'
    required: false
  elm_compiler:
    description: 'Specify the path to the elm compiler.'
    required: false
  elm_format:
    description: 'Specify the path to elm-format.'
    required: false
  elm_json:
    description: 'Specify the path to the elm.json file of the project. By default, the one in the current directory or its parent directories will be used.'
    required: false
  elm_files:
    description: 'List of Elm files you wish to review'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
